### ISSUE TITLE
the first line of the docstring in manual

### ISSUE THREAD

**Issue by arbipher** [ocaml/ocaml.org#400]
I am reading the document for `LTerm_dlist`.

The first line of the docstring is `(** Mutable sequence of elements (deprecated) *)` is at [line 10](https://github.com/ocaml-community/lambda-term/blob/27238e7b63bedae627d76e528119c93b0b0a60d7/src/lTerm_dlist.mli#L10) of the `mli` file.

In the v3 doc, this line is shown on the package index page (https://v3.ocaml.org/p/lambda-term/3.2.0/doc/index.html).
It's not on the page for `LTerm_dlist` (https://v3.ocaml.org/p/lambda-term/3.2.0/doc/LTerm_dlist/index.html).

As a comparison, in `lambda-term` own manual, this line is not shown on the index page (https://ocaml-community.github.io/lambda-term/3.1.0/lambda-term/index.html).
It's at the beginning of the page for `LTerm_dlist`(https://ocaml-community.github.io/lambda-term/3.1.0/lambda-term/LTerm_dlist/index.html).

I am not familiar with the convention of docstrings but the two cases are just not consistent. Personally, I prefer it on a specific module page rather than the index page.

**Comment by sabine** [comment]
The root cause of this seems to be that the preamble of a module is missing. Reported also in https://github.com/ocaml/ocaml.org/issues/203

**Comment by gpetiot** [comment]
It looks like it's fixed now.

**Comment by sabine** [comment]
Thank you @gpetiot, I overlooked this issue when I was closing related issues.

**Comment by arbipher** [comment]
The problem for the _old_(v2) official document is not fully solved, though I have no idea whether they are related to the rendering of v3 packages on the document website.

Line 16-20 of the `Format.mli` [https://github.com/ocaml/ocaml/blob/trunk/stdlib/format.mli#L18]() is 

```ocaml
(** Pretty-printing.

   If you are new to this module, see the {{!examples} examples} below.

   This module implements a pretty-printing facility to format values
```

Line 18 is missing on the document page for `Format` ([https://v2.ocaml.org/api/Format.html]())

```text
Pretty-printing.

This module implements a pretty-printing facility to format values ...
```

p.s. I made #1403 to suggest if the standard library can also be _ported_ to the (package) doc website.

**Comment by sabine** [comment]
No, the fix does not affect v2.ocaml.org.
