### ISSUE TITLE
Dashboard broken

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#946]
https://ocaml.org/dashboard returns an HTTP 500 Internal Server Error

Here is the log returned by a local run:
```shell
ocaml.org:main>make start
opam exec -- dune build --root .
opam exec -- dune exec src/ocamlorg_web/bin/main.exe
Done: 57% (948/1650, 702 left) (jobs: 0)main.exe: [INFO] Package state loaded (4182 packages, opam commit 59abe7be7457eed1c245c61034a50a1551f235ed)
22.02.23 18:52:01.428                       Running on 0.0.0.0:8080 (http://localhost:8080)
22.02.23 18:52:01.428                       Type Ctrl+C to stop
22.02.23 18:52:01.430                  INFO Opam repository is currently at 1c4baa4d5c7cfeebc37f1f0b666f269db6b13078
22.02.23 18:52:01.430                  INFO Updating opam package list
22.02.23 18:52:01.430                  INFO Calculating packages.. .
Already up-to-date.
22.02.23 18:52:05.669                  INFO Computing additional informations...
22.02.23 18:52:05.736                  INFO Dependencies...
22.02.23 18:52:14.706                  INFO Reverse dependencies...
22.02.23 18:52:14.710       dream.log  INFO REQ 1 GET /dashboard 127.0.0.1:57522 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
22.02.23 18:52:14.710                 ERROR REQ 1 The Metrics src for loadavg could not be found. Did you call "init_metrics ()"?
22.02.23 18:52:14.710                 ERROR REQ 1 The Metrics src for memory could not be found. Did you call "init_metrics ()"?
22.02.23 18:52:14.710       dream.log  WARN REQ 1 Aborted by: Timedesc__Printers.Invalid_format_string(": string")
22.02.23 18:52:14.710       dream.log  WARN Raised at Timedesc__Printers.invalid_format_string in file "timedesc/printers.ml", line 280, characters 30-61
22.02.23 18:52:14.710       dream.log  WARN Called from Stdlib__Format.kasprintf.k in file "format.ml", line 1391, characters 4-22
22.02.23 18:52:14.710       dream.log  WARN Called from Dream_dashboard.Handler.overview in file "src/dream_dashboard/dream_dashboard.ml", line 25, characters 54-77
22.02.23 18:52:14.710       dream.log  WARN Called from Lwt.Sequence_associated_storage.with_value in file "src/core/lwt.ml", line 804, characters 19-23
22.02.23 18:52:14.710       dream.log  WARN Re-raised at Lwt.Sequence_associated_storage.with_value in file "src/core/lwt.ml", line 809, characters 6-15
22.02.23 18:52:14.710       dream.log  WARN Called from Lwt.Sequential_composition.try_bind in file "src/core/lwt.ml", line 2118, characters 16-20
22.02.23 18:52:14.710      dream.http ERROR REQ 1 Timedesc__Printers.Invalid_format_string(": string")
22.02.23 18:52:14.710      dream.http ERROR REQ 1 Raised at Stdlib__Map.Make.find in file "map.ml", line 137, characters 10-25
22.02.23 18:52:14.710      dream.http ERROR REQ 1 Called from Logs.Tag.find in file "src/logs.ml", line 154, characters 14-32
```

**Comment by cuihtlauac** [comment]
Fixed by https://github.com/ocaml/ocaml.org/pull/954

**Comment by darrenldl** [comment]
Ah, seems like this is because I wrote the internal format string incorrectly - I'll push a fix for timedesc 1.1.1 and update the  test suite to test it.

(After 200 something tests, some bugs still escape, naturally.)

EDIT: okay, it's the format string parser's problem, and a fix has been pushed to main. I'll open a PR here when it lands on opam.
